/**
 * Historical Invoice Fee Backfill / Regeneration Script
 * ─────────────────────────────────────────────────────
 * Recomputes the monetary figures for EXISTING invoices in `tbl_invoice`
 * using the CURRENT (fixed) invoice logic (`computeInvoiceFigures`), and
 * corrects rows whose stored figures are wrong.
 *
 * WHY: older invoices were generated by buggy code that looked up the USD
 * fee tier against the crypto-denominated `base_amount` (e.g. 0.00058 BTC),
 * so `fixed_fee` collapsed to $0.00 for crypto payments (and for amounts in
 * a tier gap). This backfill recomputes fixed_fee / unit_price / vat / totals
 * from each transaction's `usd_value` and normalises the row to v2 semantics.
 *
 * SAFETY:
 *   • DRY-RUN by default — prints a full before/after diff and writes NOTHING.
 *   • Pass `--apply` to actually UPDATE the rows.
 *   • Before applying, a JSON backup of every changed row's OLD values is
 *     written to scripts/backfill_invoice_fees_backup_<timestamp>.json.
 *   • Idempotent — only rows whose recomputed values differ are touched, so
 *     re-running after an apply is a no-op.
 *   • Optional `--id=<invoice_id>` to limit to a single invoice.
 *
 * NOTE ON FX: recomputation converts USD → the company's preferred display
 * currency at TODAY's rate. For USD-preferred merchants (rate = 1) this is
 * exact. For non-USD merchants the displayed amounts are re-based at current
 * FX — the script prints a WARNING for those rows so you can decide.
 *
 * Usage:
 *   cd /app/backend && npx ts-node --transpile-only scripts/backfill_invoice_fees.ts            # dry-run
 *   cd /app/backend && npx ts-node --transpile-only scripts/backfill_invoice_fees.ts --apply    # write
 *   cd /app/backend && npx ts-node --transpile-only scripts/backfill_invoice_fees.ts --id=42    # single invoice
 */

import dotenv from "dotenv";
dotenv.config();

import fs from "fs";
import path from "path";
import sequelize from "../utils/dbInstance";
import { QueryTypes } from "sequelize";
import { computeInvoiceFigures } from "../controller/invoiceController";

const APPLY = process.argv.includes("--apply");
const idArg = process.argv.find((a) => a.startsWith("--id="));
const ONLY_ID = idArg ? parseInt(idArg.split("=")[1], 10) : null;

// Fields we recompute + the fig property each maps to + the DB column scale
// (so idempotency comparison rounds to the same precision the column stores).
const FIELD_MAP: Array<{ col: string; fig: string; scale: number }> = [
  { col: "fixed_fee", fig: "displayFixedFee", scale: 2 },
  { col: "transaction_fee_percent", fig: "transactionFeePercent", scale: 2 },
  { col: "unit_price", fig: "unitPrice", scale: 8 },
  { col: "vat_rate", fig: "vatRate", scale: 2 },
  { col: "vat_amount", fig: "displayVatAmount", scale: 2 },
  { col: "total_usd", fig: "totalAmount", scale: 2 },
  { col: "transaction_amount", fig: "displayBaseAmount", scale: 8 },
];

const roundTo = (v: any, scale: number): number => {
  const f = 10 ** scale;
  return Math.round((parseFloat(v ?? 0) || 0) * f) / f;
};
const r6 = (v: any): number => roundTo(v, 6);
// Two values differ only if they disagree at the column's stored precision.
const differs = (a: any, b: any, scale: number): boolean =>
  roundTo(a, scale) !== roundTo(b, scale);

async function main() {
  console.log("\n🧾 Invoice Fee Backfill / Regeneration");
  console.log("=".repeat(70));
  console.log(`Mode: ${APPLY ? "APPLY (will write to DB)" : "DRY-RUN (no writes)"}`);
  if (ONLY_ID) console.log(`Scope: single invoice_id=${ONLY_ID}`);
  console.log("=".repeat(70));

  const where = ONLY_ID ? `WHERE invoice_id = ${ONLY_ID}` : "";
  const invoices = (await sequelize.query(
    `SELECT invoice_id, invoice_number, transaction_id, company_id,
            invoice_version, unit_price, fixed_fee, transaction_fee_percent,
            transaction_amount, vat_rate, vat_amount, total_usd
     FROM tbl_invoice ${where}
     ORDER BY invoice_id ASC`,
    { type: QueryTypes.SELECT }
  )) as Array<Record<string, any>>;

  console.log(`\nFound ${invoices.length} invoice(s) to inspect.\n`);

  const changes: Array<{
    invoice_id: number;
    invoice_number: string;
    old: Record<string, any>;
    new: Record<string, any>;
    fxWarning: boolean;
  }> = [];

  for (const inv of invoices) {
    // Load the source transaction + company (same lookups autoGenerateInvoice uses).
    const [tx] = (await sequelize.query(
      `SELECT * FROM tbl_user_transaction WHERE transaction_id = :tid LIMIT 1`,
      { replacements: { tid: inv.transaction_id }, type: QueryTypes.SELECT }
    )) as Array<Record<string, any>>;

    if (!tx) {
      console.log(`⚠️  ${inv.invoice_number}: transaction ${inv.transaction_id} not found — SKIPPED`);
      continue;
    }

    const [company] = (await sequelize.query(
      `SELECT * FROM tbl_company WHERE company_id = :cid LIMIT 1`,
      { replacements: { cid: inv.company_id }, type: QueryTypes.SELECT }
    )) as Array<Record<string, any>>;

    if (!company) {
      console.log(`⚠️  ${inv.invoice_number}: company ${inv.company_id} not found — SKIPPED`);
      continue;
    }

    let fig: any;
    try {
      fig = await computeInvoiceFigures(tx, company, inv.company_id);
    } catch (e: any) {
      console.log(`❌ ${inv.invoice_number}: compute failed (${e.message}) — SKIPPED`);
      continue;
    }

    // Build old/new field maps + detect diffs.
    const oldVals: Record<string, any> = { invoice_version: inv.invoice_version };
    const newVals: Record<string, any> = { invoice_version: "v2" };
    let changed = inv.invoice_version !== "v2";

    for (const { col, fig: figKey, scale } of FIELD_MAP) {
      oldVals[col] = inv[col];
      newVals[col] = fig[figKey];
      if (differs(inv[col], fig[figKey], scale)) changed = true;
    }

    const fxWarning = fig.displayCurrency !== "USD";

    if (!changed) {
      console.log(`✓ ${inv.invoice_number}: already correct — no change`);
      continue;
    }

    changes.push({
      invoice_id: inv.invoice_id,
      invoice_number: inv.invoice_number,
      old: oldVals,
      new: newVals,
      fxWarning,
    });

    console.log(`\n▶ ${inv.invoice_number} (invoice_id=${inv.invoice_id}, tx=${inv.transaction_id}, ${tx.base_currency} usd_value=${tx.usd_value})`);
    if (fxWarning) {
      console.log(`   ⚠️  display currency = ${fig.displayCurrency} — figures re-based at CURRENT FX (not invoice-date FX).`);
    }
    console.log(`   version:  ${oldVals.invoice_version}  →  ${newVals.invoice_version}`);
    for (const { col, scale } of FIELD_MAP) {
      if (differs(oldVals[col], newVals[col], scale)) {
        console.log(`   ${col.padEnd(24)} ${String(r6(oldVals[col])).padStart(14)}  →  ${String(r6(newVals[col])).padStart(14)}`);
      }
    }
  }

  console.log("\n" + "=".repeat(70));
  console.log(`Invoices needing correction: ${changes.length} / ${invoices.length}`);
  console.log("=".repeat(70));

  if (changes.length === 0) {
    console.log("✅ Nothing to do.");
    return;
  }

  if (!APPLY) {
    console.log("\nDRY-RUN complete — no rows were modified.");
    console.log("Re-run with --apply to write these corrections.");
    return;
  }

  // ── APPLY ──────────────────────────────────────────────────────────────
  const ts = new Date().toISOString().replace(/[:.]/g, "-");
  const backupPath = path.join(__dirname, `backfill_invoice_fees_backup_${ts}.json`);
  fs.writeFileSync(
    backupPath,
    JSON.stringify({ created_at: new Date().toISOString(), changes }, null, 2)
  );
  console.log(`\n💾 Backup of OLD values written to: ${backupPath}`);

  const t = await sequelize.transaction();
  try {
    let applied = 0;
    for (const ch of changes) {
      await sequelize.query(
        `UPDATE tbl_invoice SET
           fixed_fee = :fixed_fee,
           transaction_fee_percent = :transaction_fee_percent,
           unit_price = :unit_price,
           vat_rate = :vat_rate,
           vat_amount = :vat_amount,
           total_usd = :total_usd,
           transaction_amount = :transaction_amount,
           invoice_version = :invoice_version
         WHERE invoice_id = :invoice_id`,
        {
          replacements: {
            fixed_fee: ch.new.fixed_fee,
            transaction_fee_percent: ch.new.transaction_fee_percent,
            unit_price: ch.new.unit_price,
            vat_rate: ch.new.vat_rate,
            vat_amount: ch.new.vat_amount,
            total_usd: ch.new.total_usd,
            transaction_amount: ch.new.transaction_amount,
            invoice_version: ch.new.invoice_version,
            invoice_id: ch.invoice_id,
          },
          type: QueryTypes.UPDATE,
          transaction: t,
        }
      );
      applied++;
    }
    await t.commit();
    console.log(`\n✅ APPLIED corrections to ${applied} invoice(s).`);
    console.log(`   (Backup for rollback: ${backupPath})`);
  } catch (e: any) {
    await t.rollback();
    console.error(`\n❌ Apply failed, transaction rolled back: ${e.message}`);
    throw e;
  }
}

if (require.main === module) {
  main()
    .then(() => {
      console.log("\nDone.");
      process.exit(0);
    })
    .catch((err) => {
      console.error("Fatal:", err);
      process.exit(1);
    });
}

export { main as backfillInvoiceFees };
