import React from "react";
import { SD_MARK } from "./brand/sdLogoData";
import { SdMark, SD_BRAND_INK, SD_BRAND_WHITE } from "./brand/SdMark";

/**
 * SafeDeal symbol ("The Hold"): an S built from two halves — buyer and seller — holding a
 * small gold square, the money in escrow. Generated by scripts/brand/safedeal-logo.mjs.
 * `onDark` swaps the halves to white for ink surfaces; the gold accent stays.
 */
export default function SafeDealMark({ size = 32, onDark = false }: { size?: number; onDark?: boolean }) {
  return <SdMark mark={SD_MARK} size={size} ink={onDark ? SD_BRAND_WHITE : SD_BRAND_INK} />;
}
