#!/usr/bin/env python3
"""Inject landing v6 slice 3–5 i18n keys (story · numbers · proof · global · dev · pricing · resources · faq · final · footer · nav) into all 6 locales. Idempotent."""
import json, os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

V6 = {
    "en": {
        "story": {"eyebrow": "How it works", "headline": "Buyer pays in Bitcoin. You receive USDC. In your own wallet.", "body": "One path for every payment: the buyer sends any supported coin, the network confirms, and settlement lands at an address you control — as the coin itself, or auto-converted to a stablecoin.", "buyerPays": "Buyer pays", "yourWallet": "Your wallet", "autoConvert": "Auto-convert", "on": "on", "keepCoin": "or keep the coin — your choice", "confirmed": "Confirmed", "detected": "Detected", "settled": "settled", "nonCustodial": "Non-custodial — we never hold your funds.", "anyWallet": "From any wallet, in any supported coin."},
        "numbers": {"eyebrow": "By the numbers", "headline": "Live figures, not marketing.", "body": "Every number below is read from production when this page is served — no rounding up, no placeholders.", "chartTitle": "Settled payments by chain", "chartSub": "Last 30 days · share of payments", "chartNote": "Counts by settlement chain, anonymised. Stablecoins on Tron and Ethereum are grouped with their chain.", "live": "Live", "other": "Other", "checks": "{{n}} checks", "settleMeta": "Solana · XRP · Tron · Polygon · Ethereum", "countriesMeta": "Merchants, by signup country"},
        "proof": {"langsT": "Checkout in six languages", "langsD": "Every buyer sees the pay sheet in their own language — English, German, Spanish, French, Portuguese and Dutch.", "langsCta": "Open the live demo"},
        "global": {"noList": "No country list to apply to", "noBank": "No bank approval to wait for", "anyWallet": "Any wallet, anywhere"},
        "dev": {"headline": "Three ways in. Pick your depth.", "body": "Start with no code today and go deeper whenever you need to — same account, same payments, same wallet.", "nocode": {"eyebrow": "No code", "t": "Links & dashboard", "d": "Create payment links, invoices, a storefront or a donation page from the dashboard. Nothing to install.", "cta": "Create your first link"}, "prebuilt": {"eyebrow": "Pre-built", "t": "Buy button & embeds", "d": "One line of HTML puts a crypto checkout on any site. Publishable keys keep your secret key off the browser.", "cta": "Get the snippet"}, "api": {"eyebrow": "Build your own", "t": "REST API & webhooks", "d": "Create payments from your backend, redirect the buyer, listen for signed webhooks. No SDK lock-in.", "cta": "Read the API docs"}},
        "pricing": {"teaserNote": "Network fees go to the blockchain and are shown before the buyer pays. The side-by-side comparison with cards and custodial gateways lives on the fees page.", "cta": "See the full fee schedule"},
        "resources": {"eyebrow": "Resources", "headline": "Guides from the team.", "body": "Integration walkthroughs, cost breakdowns and product notes — published, not promised.", "readMore": "Read", "allPosts": "All posts", "guide": "Guide", "docs": "Docs", "howtoT": "Set up a wallet and take your first payment", "howtoD": "The step-by-step path new merchants follow — wallet, first link, first settlement.", "docsT": "API reference", "docsD": "Every merchant endpoint, request and webhook payload, documented before you sign up.", "prev": "Previous", "next": "Next"},
        "faq": {"coins": {"q": "Which coins can my buyers pay with?", "a": "Bitcoin, Ethereum, Solana, XRP, Litecoin, Dogecoin, Bitcoin Cash, TRX and POL, plus USDT, USDC and RLUSD on the cheapest rails — Tron, Polygon, Ethereum and the XRP Ledger. You choose which to accept; the checkout only shows coins you have added a wallet for."}, "setup": {"q": "How long does setup take?", "a": "About five minutes for a payment link: create an account, add a payout wallet address, share the link. A buy button is one line of HTML. A full API integration is one request plus a webhook endpoint — most teams ship it in an afternoon."}, "more": "More questions are answered in Help & Support"},
        "final": {"pricingT": "See pricing", "pricingD": "One percentage that drops as you grow. No monthly fee, no setup fee, no chargebacks.", "buildT": "Start building", "buildD": "One request creates a payment. Sandbox keys, signed webhooks and public docs."},
        "footer": {"products": "Products", "developers": "Developers", "legal": "Legal", "links": "Payment links", "checkout": "Hosted checkout", "storefront": "Storefront", "donations": "Donations & tips", "invoices": "Invoices", "embeds": "Buy button", "api": "API reference", "webhooks": "Webhooks", "howto": "How-to guide", "aml": "AML policy", "about": "About", "press": "Press", "walletSecurity": "Wallet security"},
        "nav": {"solutions": "Solutions", "pricing": "Pricing", "donationsDesc": "Campaigns, tip jars and donation pages that settle to your wallet", "invoicesDesc": "Pay-in-crypto invoices with receipts and tax lines", "vert": {"ecommerce": "Crypto checkout for online stores", "saas": "Subscriptions and one-off plans, paid in crypto", "freelancers": "Invoice clients anywhere, get paid in crypto", "digitalDownloads": "Sell files and licence keys with instant delivery", "marketplaces": "Take payments from buyers in any country", "nonprofits": "Accept donations with no card fees or chargebacks"}, "creatorsFeatured": {"title": "For creators", "desc": "Tip jars, storefronts and donation pages that settle straight to your wallet.", "cta": "See creator pages"}},
        "_v3nav_global": "Global",
    },
    "de": {
        "story": {"eyebrow": "So funktioniert es", "headline": "Der Käufer zahlt in Bitcoin. Du erhältst USDC. In deiner eigenen Wallet.", "body": "Ein Weg für jede Zahlung: Der Käufer sendet einen unterstützten Coin, das Netzwerk bestätigt, und die Abrechnung landet an einer Adresse, die du kontrollierst — als der Coin selbst oder automatisch in einen Stablecoin umgewandelt.", "buyerPays": "Käufer zahlt", "yourWallet": "Deine Wallet", "autoConvert": "Auto-Umwandlung", "on": "an", "keepCoin": "oder den Coin behalten — deine Wahl", "confirmed": "Bestätigt", "detected": "Erkannt", "settled": "abgerechnet", "nonCustodial": "Non-custodial — wir halten dein Geld nie.", "anyWallet": "Aus jeder Wallet, in jedem unterstützten Coin."},
        "numbers": {"eyebrow": "In Zahlen", "headline": "Live-Werte, kein Marketing.", "body": "Jede Zahl unten wird beim Ausliefern dieser Seite aus der Produktion gelesen — nicht aufgerundet, keine Platzhalter.", "chartTitle": "Abgerechnete Zahlungen nach Chain", "chartSub": "Letzte 30 Tage · Anteil der Zahlungen", "chartNote": "Anzahl nach Abrechnungs-Chain, anonymisiert. Stablecoins auf Tron und Ethereum werden ihrer Chain zugeordnet.", "live": "Live", "other": "Andere", "checks": "{{n}} Prüfungen", "settleMeta": "Solana · XRP · Tron · Polygon · Ethereum", "countriesMeta": "Händler, nach Registrierungsland"},
        "proof": {"langsT": "Checkout in sechs Sprachen", "langsD": "Jeder Käufer sieht die Zahlungsseite in seiner Sprache — Englisch, Deutsch, Spanisch, Französisch, Portugiesisch und Niederländisch.", "langsCta": "Live-Demo öffnen"},
        "global": {"noList": "Keine Länderliste, keine Bewerbung", "noBank": "Keine Bankfreigabe abwarten", "anyWallet": "Jede Wallet, überall"},
        "dev": {"headline": "Drei Wege hinein. Du wählst die Tiefe.", "body": "Starte heute ohne Code und gehe tiefer, wann immer du willst — gleicher Account, gleiche Zahlungen, gleiche Wallet.", "nocode": {"eyebrow": "Ohne Code", "t": "Links & Dashboard", "d": "Erstelle Zahlungslinks, Rechnungen, einen Shop oder eine Spendenseite direkt im Dashboard. Nichts zu installieren.", "cta": "Ersten Link erstellen"}, "prebuilt": {"eyebrow": "Vorgefertigt", "t": "Kaufen-Button & Embeds", "d": "Eine Zeile HTML bringt einen Krypto-Checkout auf jede Website. Publishable Keys halten deinen Secret Key aus dem Browser.", "cta": "Snippet holen"}, "api": {"eyebrow": "Selbst bauen", "t": "REST-API & Webhooks", "d": "Erstelle Zahlungen aus deinem Backend, leite den Käufer weiter und empfange signierte Webhooks. Kein SDK-Lock-in.", "cta": "API-Doku lesen"}},
        "pricing": {"teaserNote": "Netzwerkgebühren gehen an die Blockchain und werden vor der Zahlung angezeigt. Den direkten Vergleich mit Karten und Custodial-Gateways findest du auf der Gebührenseite.", "cta": "Vollständige Gebührenübersicht ansehen"},
        "resources": {"eyebrow": "Ressourcen", "headline": "Guides vom Team.", "body": "Integrations-Anleitungen, Kostenvergleiche und Produktnotizen — veröffentlicht, nicht versprochen.", "readMore": "Lesen", "allPosts": "Alle Beiträge", "guide": "Guide", "docs": "Doku", "howtoT": "Wallet einrichten und die erste Zahlung annehmen", "howtoD": "Der Schritt-für-Schritt-Weg für neue Händler — Wallet, erster Link, erste Abrechnung.", "docsT": "API-Referenz", "docsD": "Jeder Händler-Endpunkt, jede Anfrage und jede Webhook-Payload — dokumentiert, bevor du dich registrierst.", "prev": "Zurück", "next": "Weiter"},
        "faq": {"coins": {"q": "Mit welchen Coins können meine Käufer zahlen?", "a": "Bitcoin, Ethereum, Solana, XRP, Litecoin, Dogecoin, Bitcoin Cash, TRX und POL sowie USDT, USDC und RLUSD auf den günstigsten Netzwerken — Tron, Polygon, Ethereum und XRP Ledger. Du wählst, was du akzeptierst; der Checkout zeigt nur Coins, für die du eine Wallet hinterlegt hast."}, "setup": {"q": "Wie lange dauert die Einrichtung?", "a": "Etwa fünf Minuten für einen Zahlungslink: Account erstellen, Auszahlungsadresse hinzufügen, Link teilen. Ein Kaufen-Button ist eine Zeile HTML. Eine vollständige API-Integration ist eine Anfrage plus ein Webhook-Endpunkt — die meisten Teams schaffen das an einem Nachmittag."}, "more": "Weitere Fragen beantworten wir im Hilfe-Center"},
        "final": {"pricingT": "Preise ansehen", "pricingD": "Ein Prozentsatz, der mit deinem Wachstum sinkt. Keine Monatsgebühr, keine Einrichtungsgebühr, keine Chargebacks.", "buildT": "Loslegen mit der API", "buildD": "Eine Anfrage erstellt eine Zahlung. Sandbox-Keys, signierte Webhooks und öffentliche Doku."},
        "footer": {"products": "Produkte", "developers": "Entwickler", "legal": "Rechtliches", "links": "Zahlungslinks", "checkout": "Gehosteter Checkout", "storefront": "Shop-Seite", "donations": "Spenden & Trinkgeld", "invoices": "Rechnungen", "embeds": "Kaufen-Button", "api": "API-Referenz", "webhooks": "Webhooks", "howto": "Anleitung", "aml": "AML-Richtlinie", "about": "Über uns", "press": "Presse", "walletSecurity": "Wallet-Sicherheit"},
        "nav": {"solutions": "Lösungen", "pricing": "Preise", "donationsDesc": "Kampagnen, Trinkgeldkassen und Spendenseiten, die in deine Wallet abrechnen", "invoicesDesc": "Rechnungen mit Krypto-Zahlung, Belegen und Steuerzeilen", "vert": {"ecommerce": "Krypto-Checkout für Online-Shops", "saas": "Abos und Einmalpläne, in Krypto bezahlt", "freelancers": "Kunden weltweit in Rechnung stellen, in Krypto bezahlt werden", "digitalDownloads": "Dateien und Lizenzschlüssel mit Sofortlieferung verkaufen", "marketplaces": "Zahlungen von Käufern aus jedem Land annehmen", "nonprofits": "Spenden ohne Kartengebühren oder Chargebacks annehmen"}, "creatorsFeatured": {"title": "Für Creator", "desc": "Trinkgeldkassen, Shops und Spendenseiten, die direkt in deine Wallet abrechnen.", "cta": "Creator-Seiten ansehen"}},
        "_v3nav_global": "Global",
    },
    "es": {
        "story": {"eyebrow": "Cómo funciona", "headline": "El comprador paga en Bitcoin. Tú recibes USDC. En tu propia wallet.", "body": "Un solo camino para cada pago: el comprador envía cualquier moneda compatible, la red confirma y la liquidación llega a una dirección que tú controlas — como la propia moneda o convertida automáticamente a una stablecoin.", "buyerPays": "El comprador paga", "yourWallet": "Tu wallet", "autoConvert": "Conversión automática", "on": "activa", "keepCoin": "o quédate con la moneda — tú eliges", "confirmed": "Confirmado", "detected": "Detectado", "settled": "liquidado", "nonCustodial": "Sin custodia — nunca retenemos tus fondos.", "anyWallet": "Desde cualquier wallet, en cualquier moneda compatible."},
        "numbers": {"eyebrow": "En cifras", "headline": "Datos en vivo, no marketing.", "body": "Cada cifra de abajo se lee de producción cuando se sirve esta página — sin redondeos al alza ni marcadores de posición.", "chartTitle": "Pagos liquidados por cadena", "chartSub": "Últimos 30 días · cuota de pagos", "chartNote": "Recuento por cadena de liquidación, anonimizado. Las stablecoins en Tron y Ethereum se agrupan con su cadena.", "live": "En vivo", "other": "Otras", "checks": "{{n}} comprobaciones", "settleMeta": "Solana · XRP · Tron · Polygon · Ethereum", "countriesMeta": "Comercios, por país de registro"},
        "proof": {"langsT": "Checkout en seis idiomas", "langsD": "Cada comprador ve la página de pago en su idioma — inglés, alemán, español, francés, portugués y neerlandés.", "langsCta": "Abrir la demo en vivo"},
        "global": {"noList": "Sin lista de países a la que aplicar", "noBank": "Sin esperar la aprobación de un banco", "anyWallet": "Cualquier wallet, en cualquier lugar"},
        "dev": {"headline": "Tres formas de entrar. Elige tu profundidad.", "body": "Empieza hoy sin código y profundiza cuando lo necesites — la misma cuenta, los mismos pagos, la misma wallet.", "nocode": {"eyebrow": "Sin código", "t": "Enlaces y panel", "d": "Crea enlaces de pago, facturas, una tienda o una página de donaciones desde el panel. Nada que instalar.", "cta": "Crea tu primer enlace"}, "prebuilt": {"eyebrow": "Prediseñado", "t": "Botón de compra y embeds", "d": "Una línea de HTML pone un checkout cripto en cualquier sitio. Las claves publicables mantienen tu clave secreta fuera del navegador.", "cta": "Obtener el snippet"}, "api": {"eyebrow": "Construye el tuyo", "t": "API REST y webhooks", "d": "Crea pagos desde tu backend, redirige al comprador y escucha webhooks firmados. Sin dependencia de un SDK.", "cta": "Leer la documentación de la API"}},
        "pricing": {"teaserNote": "Las comisiones de red van a la blockchain y se muestran antes de que el comprador pague. La comparativa con tarjetas y pasarelas con custodia está en la página de tarifas.", "cta": "Ver todas las tarifas"},
        "resources": {"eyebrow": "Recursos", "headline": "Guías del equipo.", "body": "Tutoriales de integración, desgloses de costes y notas de producto — publicados, no prometidos.", "readMore": "Leer", "allPosts": "Todas las publicaciones", "guide": "Guía", "docs": "Docs", "howtoT": "Configura una wallet y recibe tu primer pago", "howtoD": "El camino paso a paso que siguen los nuevos comercios — wallet, primer enlace, primera liquidación.", "docsT": "Referencia de la API", "docsD": "Cada endpoint, solicitud y payload de webhook, documentados antes de registrarte.", "prev": "Anterior", "next": "Siguiente"},
        "faq": {"coins": {"q": "¿Con qué monedas pueden pagar mis compradores?", "a": "Bitcoin, Ethereum, Solana, XRP, Litecoin, Dogecoin, Bitcoin Cash, TRX y POL, además de USDT, USDC y RLUSD en las redes más baratas — Tron, Polygon, Ethereum y XRP Ledger. Tú eliges cuáles aceptar; el checkout solo muestra las monedas para las que has añadido una wallet."}, "setup": {"q": "¿Cuánto tarda la configuración?", "a": "Unos cinco minutos para un enlace de pago: crea una cuenta, añade una dirección de wallet de cobro y comparte el enlace. Un botón de compra es una línea de HTML. Una integración completa por API es una solicitud más un endpoint de webhook — la mayoría de los equipos lo hace en una tarde."}, "more": "Respondemos más preguntas en Ayuda y soporte"},
        "final": {"pricingT": "Ver precios", "pricingD": "Un solo porcentaje que baja a medida que creces. Sin cuota mensual, sin alta, sin contracargos.", "buildT": "Empieza a construir", "buildD": "Una solicitud crea un pago. Claves sandbox, webhooks firmados y documentación pública."},
        "footer": {"products": "Productos", "developers": "Desarrolladores", "legal": "Legal", "links": "Enlaces de pago", "checkout": "Checkout alojado", "storefront": "Tienda", "donations": "Donaciones y propinas", "invoices": "Facturas", "embeds": "Botón de compra", "api": "Referencia de la API", "webhooks": "Webhooks", "howto": "Guía paso a paso", "aml": "Política AML", "about": "Sobre nosotros", "press": "Prensa", "walletSecurity": "Seguridad de la wallet"},
        "nav": {"solutions": "Soluciones", "pricing": "Precios", "donationsDesc": "Campañas, botes de propinas y páginas de donación que liquidan en tu wallet", "invoicesDesc": "Facturas pagaderas en cripto con recibos y líneas de impuestos", "vert": {"ecommerce": "Checkout cripto para tiendas online", "saas": "Suscripciones y planes únicos, pagados en cripto", "freelancers": "Factura a clientes de cualquier lugar y cobra en cripto", "digitalDownloads": "Vende archivos y claves de licencia con entrega instantánea", "marketplaces": "Acepta pagos de compradores de cualquier país", "nonprofits": "Acepta donaciones sin comisiones de tarjeta ni contracargos"}, "creatorsFeatured": {"title": "Para creadores", "desc": "Botes de propinas, tiendas y páginas de donación que liquidan directamente en tu wallet.", "cta": "Ver páginas de creador"}},
        "_v3nav_global": "Global",
    },
    "fr": {
        "story": {"eyebrow": "Comment ça marche", "headline": "L'acheteur paie en Bitcoin. Vous recevez des USDC. Dans votre propre wallet.", "body": "Un seul parcours pour chaque paiement : l'acheteur envoie n'importe quelle crypto prise en charge, le réseau confirme, et le règlement arrive à une adresse que vous contrôlez — dans la crypto envoyée ou convertie automatiquement en stablecoin.", "buyerPays": "L'acheteur paie", "yourWallet": "Votre wallet", "autoConvert": "Conversion auto", "on": "activée", "keepCoin": "ou gardez la crypto — à vous de choisir", "confirmed": "Confirmé", "detected": "Détecté", "settled": "réglé", "nonCustodial": "Non-custodial — nous ne détenons jamais vos fonds.", "anyWallet": "Depuis n'importe quel wallet, dans n'importe quelle crypto prise en charge."},
        "numbers": {"eyebrow": "En chiffres", "headline": "Des chiffres en direct, pas du marketing.", "body": "Chaque chiffre ci-dessous est lu en production au moment où cette page est servie — pas d'arrondi, pas de valeur factice.", "chartTitle": "Paiements réglés par chaîne", "chartSub": "30 derniers jours · part des paiements", "chartNote": "Nombre par chaîne de règlement, anonymisé. Les stablecoins sur Tron et Ethereum sont regroupés avec leur chaîne.", "live": "En direct", "other": "Autres", "checks": "{{n}} contrôles", "settleMeta": "Solana · XRP · Tron · Polygon · Ethereum", "countriesMeta": "Marchands, par pays d'inscription"},
        "proof": {"langsT": "Un checkout en six langues", "langsD": "Chaque acheteur voit la page de paiement dans sa langue — anglais, allemand, espagnol, français, portugais et néerlandais.", "langsCta": "Ouvrir la démo en direct"},
        "global": {"noList": "Aucune liste de pays à laquelle postuler", "noBank": "Aucune validation bancaire à attendre", "anyWallet": "N'importe quel wallet, n'importe où"},
        "dev": {"headline": "Trois portes d'entrée. Choisissez votre profondeur.", "body": "Commencez sans code dès aujourd'hui et allez plus loin quand vous le voulez — même compte, mêmes paiements, même wallet.", "nocode": {"eyebrow": "Sans code", "t": "Liens & tableau de bord", "d": "Créez des liens de paiement, des factures, une boutique ou une page de dons depuis le tableau de bord. Rien à installer.", "cta": "Créer votre premier lien"}, "prebuilt": {"eyebrow": "Prêt à l'emploi", "t": "Bouton d'achat & embeds", "d": "Une ligne de HTML place un checkout crypto sur n'importe quel site. Les clés publiables gardent votre clé secrète hors du navigateur.", "cta": "Récupérer le snippet"}, "api": {"eyebrow": "Sur mesure", "t": "API REST & webhooks", "d": "Créez des paiements depuis votre backend, redirigez l'acheteur, écoutez des webhooks signés. Aucune dépendance à un SDK.", "cta": "Lire la documentation API"}},
        "pricing": {"teaserNote": "Les frais de réseau vont à la blockchain et sont affichés avant que l'acheteur paie. La comparaison avec les cartes et les passerelles custodial se trouve sur la page des frais.", "cta": "Voir la grille tarifaire complète"},
        "resources": {"eyebrow": "Ressources", "headline": "Les guides de l'équipe.", "body": "Tutoriels d'intégration, analyses de coûts et notes produit — publiés, pas promis.", "readMore": "Lire", "allPosts": "Tous les articles", "guide": "Guide", "docs": "Docs", "howtoT": "Configurer un wallet et encaisser un premier paiement", "howtoD": "Le parcours pas à pas des nouveaux marchands — wallet, premier lien, premier règlement.", "docsT": "Référence API", "docsD": "Chaque endpoint marchand, chaque requête et chaque payload de webhook, documentés avant même l'inscription.", "prev": "Précédent", "next": "Suivant"},
        "faq": {"coins": {"q": "Avec quelles cryptos mes acheteurs peuvent-ils payer ?", "a": "Bitcoin, Ethereum, Solana, XRP, Litecoin, Dogecoin, Bitcoin Cash, TRX et POL, plus USDT, USDC et RLUSD sur les réseaux les moins chers — Tron, Polygon, Ethereum et XRP Ledger. Vous choisissez celles que vous acceptez ; le checkout n'affiche que les cryptos pour lesquelles vous avez ajouté un wallet."}, "setup": {"q": "Combien de temps prend la mise en place ?", "a": "Environ cinq minutes pour un lien de paiement : créez un compte, ajoutez une adresse de wallet de règlement, partagez le lien. Un bouton d'achat, c'est une ligne de HTML. Une intégration API complète, c'est une requête plus un endpoint de webhook — la plupart des équipes la livrent en un après-midi."}, "more": "D'autres questions trouvent réponse dans l'Aide & support"},
        "final": {"pricingT": "Voir les tarifs", "pricingD": "Un seul pourcentage, qui baisse à mesure que vous grandissez. Pas d'abonnement, pas de frais d'installation, pas de rétrofacturation.", "buildT": "Commencer à intégrer", "buildD": "Une requête crée un paiement. Clés sandbox, webhooks signés et documentation publique."},
        "footer": {"products": "Produits", "developers": "Développeurs", "legal": "Mentions légales", "links": "Liens de paiement", "checkout": "Checkout hébergé", "storefront": "Boutique", "donations": "Dons & pourboires", "invoices": "Factures", "embeds": "Bouton d'achat", "api": "Référence API", "webhooks": "Webhooks", "howto": "Guide pas à pas", "aml": "Politique AML", "about": "À propos", "press": "Presse", "walletSecurity": "Sécurité du wallet"},
        "nav": {"solutions": "Solutions", "pricing": "Tarifs", "donationsDesc": "Campagnes, pots à pourboires et pages de dons réglés dans votre wallet", "invoicesDesc": "Factures payables en crypto, avec reçus et lignes de taxes", "vert": {"ecommerce": "Checkout crypto pour boutiques en ligne", "saas": "Abonnements et offres ponctuelles, payés en crypto", "freelancers": "Facturez des clients partout, soyez payé en crypto", "digitalDownloads": "Vendez fichiers et clés de licence avec livraison instantanée", "marketplaces": "Encaissez des acheteurs de tous les pays", "nonprofits": "Recevez des dons sans frais de carte ni rétrofacturation"}, "creatorsFeatured": {"title": "Pour les créateurs", "desc": "Pots à pourboires, boutiques et pages de dons réglés directement dans votre wallet.", "cta": "Voir les pages créateur"}},
        "_v3nav_global": "International",
    },
    "nl": {
        "story": {"eyebrow": "Hoe het werkt", "headline": "De koper betaalt in Bitcoin. Jij ontvangt USDC. In je eigen wallet.", "body": "Eén route voor elke betaling: de koper stuurt een ondersteunde coin, het netwerk bevestigt en de afrekening landt op een adres dat jij beheert — als de coin zelf of automatisch omgezet naar een stablecoin.", "buyerPays": "Koper betaalt", "yourWallet": "Jouw wallet", "autoConvert": "Auto-omzetten", "on": "aan", "keepCoin": "of houd de coin — jij kiest", "confirmed": "Bevestigd", "detected": "Gedetecteerd", "settled": "afgerekend", "nonCustodial": "Non-custodial — wij houden je geld nooit vast.", "anyWallet": "Vanuit elke wallet, in elke ondersteunde coin."},
        "numbers": {"eyebrow": "In cijfers", "headline": "Live cijfers, geen marketing.", "body": "Elk getal hieronder wordt uit productie gelezen op het moment dat deze pagina wordt geladen — niet naar boven afgerond, geen placeholders.", "chartTitle": "Afgerekende betalingen per chain", "chartSub": "Laatste 30 dagen · aandeel van de betalingen", "chartNote": "Aantallen per afrekenings-chain, geanonimiseerd. Stablecoins op Tron en Ethereum tellen mee bij hun chain.", "live": "Live", "other": "Overig", "checks": "{{n}} controles", "settleMeta": "Solana · XRP · Tron · Polygon · Ethereum", "countriesMeta": "Merchants, naar land van registratie"},
        "proof": {"langsT": "Checkout in zes talen", "langsD": "Elke koper ziet de betaalpagina in zijn eigen taal — Engels, Duits, Spaans, Frans, Portugees en Nederlands.", "langsCta": "Open de live demo"},
        "global": {"noList": "Geen landenlijst om je voor aan te melden", "noBank": "Geen bankgoedkeuring om op te wachten", "anyWallet": "Elke wallet, overal"},
        "dev": {"headline": "Drie manieren om te starten. Kies je diepgang.", "body": "Begin vandaag zonder code en ga dieper wanneer je wilt — hetzelfde account, dezelfde betalingen, dezelfde wallet.", "nocode": {"eyebrow": "Zonder code", "t": "Links & dashboard", "d": "Maak betaallinks, facturen, een winkel of een donatiepagina vanuit het dashboard. Niets te installeren.", "cta": "Maak je eerste link"}, "prebuilt": {"eyebrow": "Kant-en-klaar", "t": "Koopknop & embeds", "d": "Eén regel HTML zet een crypto-checkout op elke site. Publiceerbare sleutels houden je geheime sleutel uit de browser.", "cta": "Snippet ophalen"}, "api": {"eyebrow": "Zelf bouwen", "t": "REST API & webhooks", "d": "Maak betalingen vanuit je backend, stuur de koper door en luister naar ondertekende webhooks. Geen SDK-lock-in.", "cta": "Lees de API-docs"}},
        "pricing": {"teaserNote": "Netwerkkosten gaan naar de blockchain en worden getoond voordat de koper betaalt. De vergelijking met kaarten en custodial gateways staat op de tarievenpagina.", "cta": "Bekijk het volledige tarievenoverzicht"},
        "resources": {"eyebrow": "Bronnen", "headline": "Gidsen van het team.", "body": "Integratiehandleidingen, kostenanalyses en productnotities — gepubliceerd, niet beloofd.", "readMore": "Lezen", "allPosts": "Alle artikelen", "guide": "Gids", "docs": "Docs", "howtoT": "Een wallet instellen en je eerste betaling ontvangen", "howtoD": "De stap-voor-stap-route die nieuwe merchants volgen — wallet, eerste link, eerste afrekening.", "docsT": "API-referentie", "docsD": "Elk merchant-endpoint, elke request en elke webhook-payload, gedocumenteerd voordat je je registreert.", "prev": "Vorige", "next": "Volgende"},
        "faq": {"coins": {"q": "Met welke coins kunnen mijn kopers betalen?", "a": "Bitcoin, Ethereum, Solana, XRP, Litecoin, Dogecoin, Bitcoin Cash, TRX en POL, plus USDT, USDC en RLUSD op de goedkoopste netwerken — Tron, Polygon, Ethereum en XRP Ledger. Jij kiest welke je accepteert; de checkout toont alleen coins waarvoor je een wallet hebt toegevoegd."}, "setup": {"q": "Hoe lang duurt het instellen?", "a": "Ongeveer vijf minuten voor een betaallink: account aanmaken, uitbetaaladres toevoegen, link delen. Een koopknop is één regel HTML. Een volledige API-integratie is één request plus een webhook-endpoint — de meeste teams hebben dat in een middag live."}, "more": "Meer vragen beantwoorden we in Help & Support"},
        "final": {"pricingT": "Bekijk tarieven", "pricingD": "Eén percentage dat daalt naarmate je groeit. Geen maandelijkse kosten, geen setupkosten, geen chargebacks.", "buildT": "Begin met bouwen", "buildD": "Eén request maakt een betaling. Sandbox-sleutels, ondertekende webhooks en openbare docs."},
        "footer": {"products": "Producten", "developers": "Developers", "legal": "Juridisch", "links": "Betaallinks", "checkout": "Gehoste checkout", "storefront": "Winkelpagina", "donations": "Donaties & fooien", "invoices": "Facturen", "embeds": "Koopknop", "api": "API-referentie", "webhooks": "Webhooks", "howto": "Handleiding", "aml": "AML-beleid", "about": "Over ons", "press": "Pers", "walletSecurity": "Walletbeveiliging"},
        "nav": {"solutions": "Oplossingen", "pricing": "Tarieven", "donationsDesc": "Campagnes, fooienpotten en donatiepagina's die afrekenen naar je wallet", "invoicesDesc": "Facturen betaalbaar in crypto, met bonnen en btw-regels", "vert": {"ecommerce": "Crypto-checkout voor webshops", "saas": "Abonnementen en eenmalige plannen, betaald in crypto", "freelancers": "Factureer klanten overal en word betaald in crypto", "digitalDownloads": "Verkoop bestanden en licentiesleutels met directe levering", "marketplaces": "Ontvang betalingen van kopers uit elk land", "nonprofits": "Ontvang donaties zonder kaartkosten of chargebacks"}, "creatorsFeatured": {"title": "Voor creators", "desc": "Fooienpotten, winkels en donatiepagina's die rechtstreeks naar je wallet afrekenen.", "cta": "Bekijk creatorpagina's"}},
        "_v3nav_global": "Wereldwijd",
    },
    "pt": {
        "story": {"eyebrow": "Como funciona", "headline": "O comprador paga em Bitcoin. Recebe USDC. Na sua própria carteira.", "body": "Um único percurso para cada pagamento: o comprador envia qualquer moeda suportada, a rede confirma e a liquidação chega a um endereço que controla — na própria moeda ou convertida automaticamente numa stablecoin.", "buyerPays": "O comprador paga", "yourWallet": "A sua carteira", "autoConvert": "Conversão automática", "on": "ativa", "keepCoin": "ou fique com a moeda — a escolha é sua", "confirmed": "Confirmado", "detected": "Detetado", "settled": "liquidado", "nonCustodial": "Sem custódia — nunca retemos os seus fundos.", "anyWallet": "A partir de qualquer carteira, em qualquer moeda suportada."},
        "numbers": {"eyebrow": "Em números", "headline": "Valores em direto, não marketing.", "body": "Cada número abaixo é lido da produção no momento em que esta página é servida — sem arredondamentos por cima, sem valores fictícios.", "chartTitle": "Pagamentos liquidados por cadeia", "chartSub": "Últimos 30 dias · quota de pagamentos", "chartNote": "Contagem por cadeia de liquidação, anonimizada. As stablecoins em Tron e Ethereum são agrupadas com a respetiva cadeia.", "live": "Em direto", "other": "Outras", "checks": "{{n}} verificações", "settleMeta": "Solana · XRP · Tron · Polygon · Ethereum", "countriesMeta": "Comerciantes, por país de registo"},
        "proof": {"langsT": "Checkout em seis línguas", "langsD": "Cada comprador vê a página de pagamento na sua língua — inglês, alemão, espanhol, francês, português e neerlandês.", "langsCta": "Abrir a demonstração em direto"},
        "global": {"noList": "Sem lista de países a que concorrer", "noBank": "Sem esperar pela aprovação de um banco", "anyWallet": "Qualquer carteira, em qualquer lugar"},
        "dev": {"headline": "Três formas de entrar. Escolha a profundidade.", "body": "Comece hoje sem código e aprofunde quando precisar — a mesma conta, os mesmos pagamentos, a mesma carteira.", "nocode": {"eyebrow": "Sem código", "t": "Ligações e painel", "d": "Crie ligações de pagamento, faturas, uma loja ou uma página de donativos a partir do painel. Nada para instalar.", "cta": "Criar a primeira ligação"}, "prebuilt": {"eyebrow": "Pré-construído", "t": "Botão de compra e embeds", "d": "Uma linha de HTML coloca um checkout cripto em qualquer site. As chaves publicáveis mantêm a sua chave secreta fora do browser.", "cta": "Obter o snippet"}, "api": {"eyebrow": "Construa o seu", "t": "API REST e webhooks", "d": "Crie pagamentos a partir do seu backend, redirecione o comprador e receba webhooks assinados. Sem dependência de SDK.", "cta": "Ler a documentação da API"}},
        "pricing": {"teaserNote": "As taxas de rede vão para a blockchain e são mostradas antes de o comprador pagar. A comparação com cartões e gateways com custódia está na página de taxas.", "cta": "Ver a tabela de taxas completa"},
        "resources": {"eyebrow": "Recursos", "headline": "Guias da equipa.", "body": "Tutoriais de integração, análises de custos e notas de produto — publicados, não prometidos.", "readMore": "Ler", "allPosts": "Todos os artigos", "guide": "Guia", "docs": "Docs", "howtoT": "Configurar uma carteira e receber o primeiro pagamento", "howtoD": "O percurso passo a passo que os novos comerciantes seguem — carteira, primeira ligação, primeira liquidação.", "docsT": "Referência da API", "docsD": "Cada endpoint, pedido e payload de webhook, documentados antes de se registar.", "prev": "Anterior", "next": "Seguinte"},
        "faq": {"coins": {"q": "Com que moedas podem pagar os meus compradores?", "a": "Bitcoin, Ethereum, Solana, XRP, Litecoin, Dogecoin, Bitcoin Cash, TRX e POL, além de USDT, USDC e RLUSD nas redes mais baratas — Tron, Polygon, Ethereum e XRP Ledger. Cabe-lhe escolher quais aceitar; o checkout mostra apenas as moedas para as quais adicionou uma carteira."}, "setup": {"q": "Quanto tempo demora a configuração?", "a": "Cerca de cinco minutos para uma ligação de pagamento: criar conta, adicionar um endereço de carteira para receber e partilhar a ligação. Um botão de compra é uma linha de HTML. Uma integração completa por API é um pedido mais um endpoint de webhook — a maioria das equipas fá-lo numa tarde."}, "more": "Respondemos a mais perguntas na Ajuda e suporte"},
        "final": {"pricingT": "Ver preços", "pricingD": "Uma única percentagem que baixa à medida que cresce. Sem mensalidade, sem taxa de adesão, sem chargebacks.", "buildT": "Começar a construir", "buildD": "Um pedido cria um pagamento. Chaves de sandbox, webhooks assinados e documentação pública."},
        "footer": {"products": "Produtos", "developers": "Programadores", "legal": "Legal", "links": "Ligações de pagamento", "checkout": "Checkout alojado", "storefront": "Loja", "donations": "Donativos e gorjetas", "invoices": "Faturas", "embeds": "Botão de compra", "api": "Referência da API", "webhooks": "Webhooks", "howto": "Guia passo a passo", "aml": "Política AML", "about": "Sobre nós", "press": "Imprensa", "walletSecurity": "Segurança da carteira"},
        "nav": {"solutions": "Soluções", "pricing": "Preços", "donationsDesc": "Campanhas, caixas de gorjetas e páginas de donativos que liquidam na sua carteira", "invoicesDesc": "Faturas pagáveis em cripto, com recibos e linhas de IVA", "vert": {"ecommerce": "Checkout cripto para lojas online", "saas": "Subscrições e planos únicos, pagos em cripto", "freelancers": "Fature clientes em qualquer lugar e receba em cripto", "digitalDownloads": "Venda ficheiros e chaves de licença com entrega imediata", "marketplaces": "Receba pagamentos de compradores de qualquer país", "nonprofits": "Receba donativos sem taxas de cartão nem chargebacks"}, "creatorsFeatured": {"title": "Para criadores", "desc": "Caixas de gorjetas, lojas e páginas de donativos que liquidam diretamente na sua carteira.", "cta": "Ver páginas de criador"}},
        "_v3nav_global": "Global",
    },
}


def deep_merge(dst: dict, src: dict) -> None:
    for k, v in src.items():
        if isinstance(v, dict):
            deep_merge(dst.setdefault(k, {}), v)
        else:
            dst[k] = v


for lang, block in V6.items():
    p = os.path.join(ROOT, "langs", "locales", lang, "landing.json")
    with open(p, encoding="utf-8") as f:
        data = json.load(f)
    block = dict(block)
    v3_global = block.pop("_v3nav_global")
    deep_merge(data.setdefault("v6", {}), block)
    data.setdefault("v3", {}).setdefault("nav", {})["global"] = v3_global
    with open(p, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
        f.write("\n")
    print(lang, "ok", sorted(data["v6"].keys()))
