// Generated by scripts/brand/generate-logo.mjs — do not edit by hand.
export const LOGO_MARK_VIEWBOX = "9 7 50 50";
/** Bold "D" ring (even-odd fill). */
export const LOGO_MARK_RING = "M14 8H30A24 24 0 0 1 30 56H14Z M22 16H30A16 16 0 0 1 30 48H22Z";
/** Right-pointing settlement arrow in the counter (same fill). */
export const LOGO_MARK_ARROW = "M23 29H33.5V24L44 32L33.5 40V35H23Z";
