// Generated by scripts/brand/generate-logo.mjs — do not edit by hand.
export const LOGO_MARK_VIEWBOX = "2.15 0.1 59.4 59.4";
/** Outer D + inner D (both open at the slot) + pill slot — stroked, one colour. */
export const LOGO_MARK_STROKES = "M16 30.5V8H28A24 24 0 0 1 28 56H16V33.5M24.6 30.5V16.6H28A15.4 15.4 0 0 1 28 47.4H24.6V33.5M11.5 28H25.8A4 4 0 0 1 25.8 36H11.5A4 4 0 0 1 11.5 28Z";
export const LOGO_MARK_STROKE_WIDTH = 5;
/** Reeded coin edge hugging the bowl (dashed arc band). */
export const LOGO_MARK_TICKS = "M36.02 4.03A29.1 29.1 0 0 1 36.02 59.97";
export const LOGO_MARK_TICK_WIDTH = 3.2;
export const LOGO_MARK_TICK_DASH = "2.7 1.0";
/** The aqua dot at the top-right (filled). */
export const LOGO_MARK_SPARK = "M49.6 5.5a4.4 4.4 0 1 0 8.8 0a4.4 4.4 0 1 0 -8.8 0Z";
